theme: auto

server:
  address: tcp://127.0.0.1:19091/

log:
  level: info

totp:
  issuer: dsh-hub

authentication_backend:
  ldap:
    implementation: lldap
    address: '{{ env "DSH_HUB_AUTHELIA_LDAP_URL" }}'
    base_dn: '{{ env "LLDAP_BASE_DN" }}'
    user: 'uid={{ env "LLDAP_ADMIN_USERNAME" }},ou=people,{{ env "LLDAP_BASE_DN" }}'

access_control:
  default_policy: deny
  rules:
    - domain:
        - '{{ env "PORTAL_HOST" }}'
        - '*.{{ env "INSTANCE_BASE_DOMAIN" }}'
      subject: 'group:{{ env "LLDAP_ADMISSION_GROUP" }}'
      policy: one_factor

session:
  cookies:
    - domain: '{{ env "BASE_DOMAIN" }}'
      authelia_url: 'https://{{ env "AUTH_HOST" }}'
      default_redirection_url: 'https://{{ env "PORTAL_HOST" }}'

storage:
  local:
    path: /config/data/db.sqlite3

notifier:
  filesystem:
    filename: /config/data/notification.txt
